<?php
$PREFERRED_BRANDS = [
  "DOLCE GABBANA","EMPORIO ARMANI","FERRARI SCUDERIA","GIORGIO ARMANI","JIMMY CHOO NEW",
  "MICHAEL KORS","MIU MIU","OAKLEY","OLIVER PEOPLES","PERSOL","PRADA","RAY BAN",
  "SWAROVSKI NEW","VALENTINO","VERSACE","VOGUE"
];
?>
